"""Collect the upstream licence texts that must ship with the binary.

MIT, BSD-2-Clause and Apache-2.0 all require the copyright notice, the
conditions and the disclaimer to travel with a *binary* redistribution. The
compiled extension statically links these crates, so the wheel is such a
redistribution. Naming the licence identifiers in an SBOM does not satisfy any
of the three -- the text itself has to be there.

The texts are read out of the vendored crate sources in the cargo registry,
not transcribed, so what ships is what upstream published.

    python scripts/collect_notices.py            # rewrite THIRD-PARTY-LICENSES.md
    python scripts/collect_notices.py --check    # fail if it is stale
"""
from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "THIRD-PARTY-LICENSES.md"

# Build-time-only crates: they run on the build machine and no part of them is
# linked into the shipped extension, so they carry no redistribution duty here.
PROC_MACRO_ONLY = {"pyo3-macros", "pyo3-macros-backend", "proc-macro2",
                   "quote", "syn", "unicode-ident", "heck", "rustc-hash"}

LICENSE_FILE = re.compile(r"^(LICENSE|LICENCE|COPYRIGHT|NOTICE)([-_.].*)?$",
                          re.IGNORECASE)


def linked_crates() -> list[tuple[str, str, str]]:
    """(name, version, spdx) for every crate in the normal dependency graph."""
    # --target all, not the host target. Without it `cargo tree` resolves the
    # platform-specific dependencies of whichever machine is running, so the
    # generated file differs between Linux, macOS and Windows and --check
    # reports "stale" on every host except the one that wrote it. The union is
    # also the honest set for a file committed once and shipped in wheels for
    # all three: over-inclusive costs a few paragraphs, under-inclusive is the
    # licence violation this script exists to prevent.
    out = subprocess.run(
        ["cargo", "tree", "--format", "{p}|{l}", "-e", "normal",
         "--prefix", "none", "--target", "all"],
        cwd=ROOT, capture_output=True, text=True, check=True).stdout
    seen: dict[tuple[str, str], str] = {}
    for line in out.splitlines():
        line = line.strip().removesuffix(" (*)")
        if "|" not in line:
            continue
        pkg, spdx = line.rsplit("|", 1)
        pkg = pkg.replace(" (proc-macro)", "").strip()
        parts = pkg.split()
        if len(parts) < 2 or not parts[1].startswith("v"):
            continue
        name, version = parts[0], parts[1][1:]
        if name == "mixedlm-rs" or name in PROC_MACRO_ONLY:
            continue
        seen[(name, version)] = spdx.strip()
    return sorted((n, v, s) for (n, v), s in seen.items())


def registry_roots() -> list[pathlib.Path]:
    home = pathlib.Path.home() / ".cargo" / "registry" / "src"
    return sorted(p for p in home.glob("*") if p.is_dir()) if home.exists() else []


def texts_for(name: str, version: str) -> list[tuple[str, str]]:
    for root in registry_roots():
        src = root / f"{name}-{version}"
        if not src.is_dir():
            continue
        found = []
        for path in sorted(src.iterdir()):
            if path.is_file() and LICENSE_FILE.match(path.name):
                body = path.read_text(encoding="utf-8", errors="replace").strip()
                if body:
                    found.append((path.name, body))
        return found
    return []


def render() -> str:
    crates = linked_crates()
    parts = [
        "# Third-party licence texts",
        "",
        "The compiled extension in the wheel statically links the Rust crates",
        "below. MIT, BSD-2-Clause and Apache-2.0 each require their copyright",
        "notice, conditions and disclaimer to accompany a binary",
        "redistribution, so the full upstream text of each is reproduced here",
        "and this file ships inside the wheel and the sdist.",
        "",
        "Generated by `scripts/collect_notices.py` from the crate sources in",
        "the local cargo registry -- these are upstream's own files, not a",
        "transcription. `THIRD-PARTY-NOTICES.md` summarises the same set and",
        "records what is *not* linked in.",
        "",
        "The crate set is the union across all targets (`cargo tree --target",
        "all`), so this file is the same on Linux, macOS and Windows and one",
        "committed copy covers every wheel. A crate that only links on one",
        "platform still appears here.",
        "",
        "Build-time-only crates (procedural macros, which run on the build",
        "machine and are not linked into the artifact) are omitted: "
        + ", ".join(sorted(PROC_MACRO_ONLY)) + ".",
        "",
        "## Crates linked into the shipped extension",
        "",
        "| crate | version | SPDX |",
        "|---|---|---|",
    ]
    parts += [f"| `{n}` | {v} | {s} |" for n, v, s in crates]
    parts.append("")

    missing = []
    for name, version, spdx in crates:
        found = texts_for(name, version)
        if not found:
            missing.append(f"{name} {version}")
            continue
        parts += ["", "---", "", f"## {name} {version}", "", f"SPDX: `{spdx}`", ""]
        for filename, body in found:
            parts += [f"### {name} {version} -- `{filename}`", "", "```", body, "```", ""]
    if missing:
        raise SystemExit(
            "no licence file found in the vendored source for: "
            + ", ".join(missing)
            + ". Run `cargo fetch` so the crate sources are present, or add "
              "the notice by hand -- shipping the binary without it is the "
              "licence violation this script exists to prevent.")
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="fail if the committed file is not what this "
                         "would generate")
    args = ap.parse_args()
    text = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT.name} is stale; run `python scripts/collect_notices.py`",
                  file=sys.stderr)
            return 1
        print(f"{OUT.name} is up to date")
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.name} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
